#spring:
#  datasource:
#    url : jdbc:mysql://localhost:3306/seat_management_system?useSSL=false
#    username : root
#    password : root

spring:
  datasource:
    url: jdbc:mysql://34.70.215.223/seatmanagement?useSSL=false
    username: gaurav1
    password: Gaurav@234
    driver-class-name: com.mysql.cj.jdbc.Driver
    socketFactory : com.google.cloud.mysql.SocketFactory
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher





  #jpa Setting
  jpa.hibernate.ddl_auto : update

server:
  port: 80


logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    org:
      springframework:
        scheduling: DEBUG